# Внимание!
# Проектные директории не указаны в секции volumes специально,
# чтобы все изменения происходили исключительно в файловой системе контейнера.
# Содержимое хоста не будет синхронизироваться с контейнером.
# Если в контейнере произойдут изменения — они не затронут файлы на диске хоста,
# и наоборот. Это обеспечивает репродуцируемость окружения и чистоту слоёв.

# Для сервиса api организован мониторинг доступности через healthcheck и 
# автоматический перезапуск в случае трёх провальных проверок.

version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: prod_api
    ports:
      - "8000:8000" # Порт для API
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"] #команда curl вызывает эндпоинт /health и завершится с ошибкой, если сервис отвечает не 200 OK
      interval: 30s  # healthcheck запускается каждые 30 секунд
      timeout: 10s   # команда test должна завершиться за 10 секунд
      retries: 3     # требуется 3 провальные проверки подряд, чтобы контейнер стал unhealthy
    restart: always # перезапуск при любом сбое, включая unhealthy

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    container_name: jupyter_full
    ports:
      - "8888:8888" # Порт для jupyter
      - "8000:8000" # Порт для API


  light:
    build:
      context: .
      dockerfile: Dockerfile.light
    container_name: cli_light
    ports:
      - "8000:8000" # Порт для API
