# САМАЯ ЛЁГКАЯ ВЕРСИЯ ОБРАЗА ДЛЯ API

# Используем официальный базовый образ с установленным Miniconda3
FROM continuumio/miniconda3

# Копируем файл зависимостей Conda (environment.yml) во временную папку внутри контейнера
COPY environment.yml /tmp/environment.yml

# Создаём новое Conda-окружение project_ml_env на основе environment.yml
RUN conda env create -f /tmp/environment.yml -n project_ml_env

# Добавляем команду активации окружения в ~/.bashrc для root,
# чтобы при каждом запуске bash автоматически активировалось нужное окружение
RUN echo "conda activate project_ml_env" >> /root/.bashrc

# Обновляем переменную среды PATH,
# чтобы бинарники окружения были доступны из любых команд
ENV PATH /opt/conda/envs/project_ml_env/bin:$PATH

# Устанавливаем рабочую директорию внутри контейнера — все команды и файлы будут относиться к /app
WORKDIR /app

# Копируем минимум файлов для работы сервиса
COPY src /app/src
# Создаём новую папку models чтобы не копировать все модели из существующей models
RUN mkdir -p /app/models
# Копируем в неё обученный пайплайн
COPY models/main_pipeline.pkl /app/models/

# Открываем порт для доступа к FastAPI
EXPOSE 8000

# Запускаем внутри контейнера сервер Uvicorn, который стартует FastAPI-приложение app 
# из файла app.py, и слушает все входящие подключения на порту 8000 снаружи и внутри контейнера.
CMD ["uvicorn", "src.app:app", "--host", "0.0.0.0", "--port", "8000"]

# Чистим кеш conda
RUN conda clean -afy


# Контейнер работает на стандартном системном аллокаторе glibc (ptmalloc2) — ничего менять нельзя, все механизмы управления памятью функций модуля memory_utils.py(malloc_trim) будут работать корректно.